### ISSUE TITLE
Status for NSD file validation

### ISSUE THREAD

**Issue by Flurb** [riseclipse/riseclipse-main#1]
Hi,

I was wondering what's the status of NSD file validation.
According to the download page (https://wdi.centralesupelec.fr/software/RiseClipse/Downloads), NSD file validation is work in progress. And the dowloadable JAR is a SNAPSHOT, not a release.

Thanks!

**Comment by marcadetd** [comment]
Hi,

Sorry, I missed this issue, I just see it now, while I wanted to add an issue here.
Even if it is still work in progress (not enough use to be sure that nothing is missing in NSD validation), it is quite complete and can be used.
Regards,
Dominique
